# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
#
# install pre-commit by pip and set python version
# install:  pre-commit install
# test:     pre-commit run --all-files
# update:   pre-commit autoupdate
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-xml
-   repo: https://github.com/IamTheFij/ansible-pre-commit
    rev: v0.1.2
    hooks:
    -   id: encryption-check
default_language_version:
    python: python3.6
